blueprint:
  name: Three-Tier Heating Control
  description: Smart heating control with comfort/eco/away/night modes based on presence detection, geo-fencing, and outdoor temperature
  domain: automation
  input:
    climate_entity:
      name: Climate Entity
      description: The thermostat or climate group to control
      selector:
        entity:
          domain: climate
    presence_sensor:
      name: Presence Sensor
      description: Binary sensor that detects presence in the room
      selector:
        entity:
          domain: binary_sensor
    person_1:
      name: Person 1
      description: First person to track
      selector:
        entity:
          domain: person
    person_2:
      name: Person 2
      description: Second person to track (optional)
      default: person.none
      selector:
        entity:
          domain: person
    distance_sensor_1:
      name: Distance Sensor Person 1
      description: Distance sensor for first person
      selector:
        entity:
          domain: sensor
    distance_sensor_2:
      name: Distance Sensor Person 2
      description: Distance sensor for second person (optional)
      default: sensor.none
      selector:
        entity:
          domain: sensor
    schedule_entity:
      name: Schedule
      description: Schedule that defines active hours (e.g., Day Time)
      selector:
        entity:
          domain: schedule
    comfort_temp:
      name: Comfort Temperature Input
      description: Input number for comfort temperature
      selector:
        entity:
          domain: input_number
    eco_temp:
      name: Eco Temperature Input
      description: Input number for eco temperature
      selector:
        entity:
          domain: input_number
    away_temp:
      name: Away Temperature Input
      description: Input number for away temperature
      selector:
        entity:
          domain: input_number
    outdoor_temp:
      name: Outdoor Temperature Sensor
      description: Outdoor temperature sensor for adaptive pre-heating
      selector:
        entity:
          domain: sensor
    humidity_sensor:
      name: Humidity Sensor
      description: Indoor humidity sensor for comfort adjustment
      selector:
        entity:
          domain: sensor
    presence_on_delay:
      name: Presence On Delay
      description: Minutes to wait before activating comfort mode
      default: 1
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes
    presence_off_delay:
      name: Presence Off Delay
      description: Minutes to wait before deactivating comfort mode
      default: 10
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input person_1
  - platform: state
    entity_id: !input person_2
  - platform: state
    entity_id: !input presence_sensor
    to: "on"
    for:
      minutes: !input presence_on_delay
  - platform: state
    entity_id: !input presence_sensor
    to: "off"
    for:
      minutes: !input presence_off_delay
  - platform: state
    entity_id: !input schedule_entity
  - platform: state
    entity_id: !input comfort_temp
  - platform: state
    entity_id: !input eco_temp
  - platform: state
    entity_id: !input away_temp
  - platform: state
    entity_id: !input outdoor_temp
  - platform: numeric_state
    entity_id: !input distance_sensor_1
    below: 2000

action:
  - choose:
      # Priority 1: Presence detected (with humidity adjustment)
      - conditions:
          - condition: state
            entity_id: !input presence_sensor
            state: "on"
            for:
              minutes: !input presence_on_delay
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: >
                {% set base = states(comfort_temp) | float %}
                {% set humidity = states(humidity_sensor) | float(50) %}
                {% if humidity > 70 %}
                  {{ (base - 1.0) | round(1) }}
                {% elif humidity > 60 %}
                  {{ (base - 0.5) | round(1) }}
                {% elif humidity < 30 %}
                  {{ (base + 0.5) | round(1) }}
                {% else %}
                  {{ base }}
                {% endif %}
      
      # Priority 2: Nobody home AND presence off
      - conditions:
          - condition: template
            value_template: >
              {% set p1 = states(person_1) %}
              {% set p2 = states(person_2) %}
              {{ p1 != 'home' and (p2 == 'person.none' or p2 != 'home') }}
          - condition: state
            entity_id: !input presence_sensor
            state: "off"
            for:
              minutes: !input presence_off_delay
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: "{{ states(away_temp) | float }}"
    
    # Priority 3: Default (night, eco, pre-heating)
    default:
      - service: climate.set_temperature
        target:
          entity_id: !input climate_entity
        data:
          temperature: >
            {% set outdoor = states(outdoor_temp) | float(10) %}
            {% set dist1 = states(distance_sensor_1) | float(99999) %}
            {% set dist2 = states(distance_sensor_2) | float(99999) %}
            {% set nearest_dist = [dist1, dist2] | min %}
            {% set eco = states(eco_temp) | float %}
            {% set away = states(away_temp) | float %}
            {% set p1 = states(person_1) %}
            {% set p2 = states(person_2) %}
            
            {# Night mode: eco - 2°C #}
            {% if is_state(schedule_entity, 'off') %}
              {{ (eco - 2) | round(1) }}
            
            {# Someone at home or within 1km: eco temp #}
            {% elif p1 == 'home' or p2 == 'home' or nearest_dist < 1000 %}
              {{ eco }}
            
            {# Pre-heating: outdoor temp based distance #}
            {% elif outdoor < 0 and nearest_dist < 2000 %}
              {{ eco }}
            {% elif outdoor < 5 and nearest_dist < 1500 %}
              {{ eco }}
            
            {# Everyone far away: away temp #}
            {% else %}
              {{ away }}
            {% endif %}

variables:
  climate_entity: !input climate_entity
  presence_sensor: !input presence_sensor
  person_1: !input person_1
  person_2: !input person_2
  distance_sensor_1: !input distance_sensor_1
  distance_sensor_2: !input distance_sensor_2
  schedule_entity: !input schedule_entity
  comfort_temp: !input comfort_temp
  eco_temp: !input eco_temp
  away_temp: !input away_temp
  outdoor_temp: !input outdoor_temp
  humidity_sensor: !input humidity_sensor
